Repository hmcts/cui-ra, pull requests merged in 2023-08, with the labels that each got.

#163 C UI ra 35
  .yarn/install-state.gz
  src/main/constants/route.ts
  src/main/controllers/homeController.ts
  src/main/resources/translation/en/common.json
  src/main/resources/translation/en/services/PFL/contact.json
  src/main/routes.ts
  src/main/views/intro.njk
  src/main/views/review.njk
  src/test/unit/data/flags-payload.json
  src/test/unit/mocks/request.ts
  src/test/unit/tests/controllers/homeController.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-163

#169 C UI ra 39
  .yarn/install-state.gz
  src/main/constants/index.ts
  src/main/constants/route.ts
  src/main/constants/status.ts
  src/main/controllers/homeController.ts
  src/main/controllers/index.ts
  src/main/controllers/reviewController.ts
  src/main/modules/awilix/index.ts
  src/main/routes.ts
  src/main/views/intro.njk
  src/main/views/overview.njk
  src/main/views/review.njk
  src/test/unit/tests/controllers/homeController.test.ts
  src/test/unit/tests/controllers/reviewController.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-169

#176 temp remove smoke tests
  .pnp.cjs
  .yarn/cache/@codeceptjs-allure-legacy-npm-1.0.2-eda18d0834-e53d684041.zip
  .yarn/cache/allure-js-commons-npm-1.3.2-0f1f7412a0-9e7433579e.zip
  .yarn/cache/file-type-npm-7.7.1-f941f0a9c4-1c4f8cb2bd.zip
  .yarn/cache/fs-extra-npm-6.0.1-fe74e3ae93-133dbd765e.zip
  .yarn/cache/js2xmlparser-npm-3.0.0-2a2e575bd8-4e0ff6b695.zip
  .yarn/cache/xmlcreate-npm-1.0.2-0203cde341-2fbe0303fa.zip
  .yarn/install-state.gz
  config/default.json
  package.json
  src/main/modules/awilix/index.ts
  src/main/modules/session/index.ts
  src/main/services/redis.ts
  src/main/views/home.njk
  src/test/functional/codecept.conf.ts
  src/test/smoke/smoke.ts
  src/test/unit/mocks/redis.ts
  src/test/unit/tests/services/redis.test.ts
  yarn.lock
Labels: ns:cui, prd:cui, rel:cui-ra-pr-176

#177 CUI ra 22
  .yarn/install-state.gz
  src/main/controllers/reviewController.ts
  src/main/interfaces/dataManager.ts
  src/main/interfaces/referenceData.ts
  src/main/managers/dataManager.ts
  src/main/models/form.ts
  src/main/processors/flagProcessor.ts
  src/main/processors/formProcessor.ts
  src/main/resources/translation/en/common.json
  src/main/services/refdata.ts
  src/main/views/components/accessible-autocomplete/template.njk
  src/main/views/forms/checkbox-group.njk
  src/main/views/forms/radio-group.njk
  src/main/views/forms/type-ahead.njk
  src/test/unit/data/data-processor-results.json
  src/test/unit/tests/processors/formProcessor.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-177

#178 C UI ra 22
  .pnp.cjs
  .yarn/cache/@ioredis-commands-npm-1.2.0-47541de88b-9b20225ba3.zip
  .yarn/cache/denque-npm-2.1.0-578d0b6297-1d4ae1d05e.zip
  .yarn/cache/ioredis-npm-5.3.2-58471071b1-9a23559133.zip
  .yarn/cache/lodash.defaults-npm-4.2.0-c5dea025ab-8492325823.zip
  .yarn/cache/lodash.isarguments-npm-3.1.0-9e74d350b8-ae1526f3eb.zip
  .yarn/cache/redis-errors-npm-1.2.0-a81fd9b0f1-f28ac26921.zip
  .yarn/cache/redis-parser-npm-3.0.0-7ebe40abcb-89290ae530.zip
  .yarn/cache/standard-as-callback-npm-2.1.0-8e47620bd4-88bec83ee2.zip
  .yarn/install-state.gz
  charts/cui-ra/values.preview.template.yaml
  package.json
  src/main/app.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/session/index.ts
  src/main/services/redis.ts
  yarn.lock
Labels: ns:cui, prd:cui, rel:cui-ra-pr-178

#182 C UI ra 22
  .yarn/install-state.gz
  charts/cui-ra/Chart.yaml
  charts/cui-ra/values.aat.template.yaml
  charts/cui-ra/values.preview.template.yaml
  config/development.json
  config/production.json
  config/test.json
  src/main/middlewares/index.ts
  src/main/middlewares/initSession.ts
  src/main/modules/health/index.ts
  src/main/modules/session/index.ts
  src/main/resources/translation/en/common.json
  src/main/routes.ts
  src/main/types/index.d.ts
  src/test/unit/tests/middlewares/initSession.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-182

#185 Update redis port to SSL
  config/default.json
Labels: ns:cui, prd:cui, rel:cui-ra-pr-185

#184 yarn install
  .yarn/install-state.gz
Labels: ns:cui, prd:cui, rel:cui-ra-pr-184

#188 Fixed partyname being blank on overview, removed action from form to …
  src/main/controllers/homeController.ts
  src/main/views/demo.njk
  src/main/views/overview.njk
Labels: ns:cui, prd:cui, rel:cui-ra-pr-188

#189 C UI ra 22
  .yarn/install-state.gz
  src/main/constants/route.ts
  src/main/controllers/demoController.ts
  src/main/routes.ts
  src/main/views/demo.njk
  src/test/unit/tests/controllers/demoController.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-189

#190 Changed form submit to get instead of post
  src/main/controllers/demoController.ts
  src/main/routes.ts
  src/main/views/demo.njk
  src/test/unit/tests/controllers/demoController.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-190

#192 changed store to always select filestore to bypass Redis until we can…
  .yarn/install-state.gz
  src/main/app.ts
  src/main/modules/session/index.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-192

#195 C UI ra 22
  .yarn/install-state.gz
  src/main/modules/session/index.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-195

#197 Numerous changes to Redis setup to attempt to fix Redis in AAT enviro…
  src/main/app.ts
  src/main/modules/session/index.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-197

#198 Added variable to change the start of the Redis url depending on envi…
  .yarn/install-state.gz
  config/default.json
  config/development.json
  src/main/modules/awilix/index.ts
  src/main/modules/session/index.ts
  src/main/services/redis.ts
  src/test/unit/tests/services/redis.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-198

#199 C UI ra 22
  src/main/modules/session/index.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-199

#201 C UI ra 22
  .yarn/install-state.gz
  src/main/modules/session/index.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-201

#202 C UI ra 22
  src/main/modules/session/index.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-202

#203 C UI ra 22
  src/main/modules/session/index.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-203

#206 C UI ra 22
  .yarn/install-state.gz
  src/main/modules/session/index.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-206

#208 amended way tls is set conditionally
  src/main/modules/session/index.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-208

#219 C UI ra 22
  .yarn/install-state.gz
  src/main/controllers/formController.ts
  src/main/managers/newFlagsManager.ts
  src/main/models/form.ts
  src/main/processors/formProcessor.ts
  src/main/views/forms/checkbox-group.njk
  src/main/views/forms/radio-group.njk
  src/main/views/forms/type-ahead.njk
  src/test/unit/tests/controllers/formController.test.ts
  src/test/unit/tests/managers/newFlagsManager.test.ts
  src/test/unit/tests/processors/formProcessor.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-219
