Repository hmcts/cui-ra, pull requests merged in 2023-06, with the labels that each got.

#34 Added file/folder structure for translation files. Added readme for s…
  src/main/resources/translation/README.md
  src/main/resources/translation/cy/common.json
  src/main/resources/translation/cy/default/contact.json
  src/main/resources/translation/cy/default/flags.json
  src/main/resources/translation/cy/errors/404.json
  src/main/resources/translation/cy/errors/500.json
  src/main/resources/translation/cy/flags.json
  src/main/resources/translation/cy/static/accessibility.json
  src/main/resources/translation/cy/static/cookies.json
  src/main/resources/translation/cy/static/privacy-policy.json
  src/main/resources/translation/cy/static/terms-and-conditions.json
  src/main/resources/translation/en/common.json
  src/main/resources/translation/en/default/contact.json
  src/main/resources/translation/en/default/flags.json
  src/main/resources/translation/en/errors/404.json
  src/main/resources/translation/en/errors/500.json
  src/main/resources/translation/en/flags.json
  src/main/resources/translation/en/static/accessibility.json
  src/main/resources/translation/en/static/cookies.json
  src/main/resources/translation/en/static/privacy-policy.json
  src/main/resources/translation/en/static/terms-and-conditions.json
Labels: ns:cui, prd:cui, rel:cui-ra-pr-34

#57 CUIRA 88
  .eslintignore
  .gitignore
  .pnp.cjs
  .yarn/cache/@otplib-core-npm-12.0.1-4b9787d379-b3c34bc20b.zip
  .yarn/cache/@otplib-plugin-crypto-npm-12.0.1-d0dc5d1d98-6867c74ee8.zip
  .yarn/cache/@otplib-plugin-thirty-two-npm-12.0.1-b85109b20e-920099e40d.zip
  .yarn/cache/@otplib-preset-default-npm-12.0.1-77f04f54c4-8133231384.zip
  .yarn/cache/@otplib-preset-v11-npm-12.0.1-df44c202c1-367cb09397.zip
  .yarn/cache/array-union-npm-3.0.1-3ee2eb5947-47b29f8825.zip
  .yarn/cache/autobind-decorator-npm-2.4.0-07ffeb9afd-6fcc922580.zip
  .yarn/cache/awilix-npm-8.0.1-5523b594b3-0cc2a236d2.zip
  .yarn/cache/copy-webpack-plugin-npm-10.2.4-c83f04e53e-87f0f4530a.zip
  .yarn/cache/copy-webpack-plugin-npm-9.1.0-ea49123db5-06cb4fb6fc.zip
  .yarn/cache/express-nunjucks-npm-3.0.1-44939c97ad-e61cde1477.zip
  .yarn/cache/express-nunjucks-npm-3.1.0-68bf7a38b4-c145d1cfeb.zip
  .yarn/cache/globby-npm-12.2.0-c8a4e97e5f-2539379a7f.zip
  .yarn/cache/otplib-npm-12.0.1-77263e8084-4a1b91cf1b.zip
  .yarn/cache/slash-npm-4.0.0-ce4bbc4a80-da8e4af737.zip
  .yarn/cache/thirty-two-npm-1.0.2-9d9270aa34-f6700b31d1.zip
  .yarn/install-state.gz
  charts/cui-ra/Chart.yaml
  charts/cui-ra/values.yaml
  config/default.json
  config/dev.json
  config/production.json
  jest.config.js
  package.json
  sonar-project.properties
  src/main/app.ts
  src/main/controllers/homeController.ts
  src/main/controllers/index.ts
  src/main/interfaces/index.ts
  src/main/interfaces/logger.ts
  src/main/modules/awilix/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/routes/home.ts
  src/main/services/index.ts
  src/main/services/s2s.ts
  src/test/unit/mocks/axios.ts
  src/test/unit/mocks/index.ts
  src/test/unit/mocks/logger.ts
  src/test/unit/mocks/request.ts
  src/test/unit/mocks/response.ts
  src/test/unit/tests/controllers/homeController.test.ts
  src/test/unit/tests/sample.ts
  src/test/unit/tests/services/s2s.test.ts
  tsconfig.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:cui, prd:cui, rel:cui-ra-pr-57

#83 C UI ra 67
  .pnp.cjs
  .yarn/install-state.gz
  bin/mount-property-volume.js
  config/default.json
  config/dev.json
  config/production.json
  package.json
  src/main/interfaces/index.ts
  src/main/interfaces/referenceData.ts
  src/main/interfaces/serviceAuth.ts
  src/main/modules/awilix/index.ts
  src/main/services/index.ts
  src/main/services/refdata.ts
  src/main/services/s2s.ts
  src/test/unit/data/flags.json
  src/test/unit/mocks/index.ts
  src/test/unit/mocks/serviceAuth.ts
  src/test/unit/tests/services/refdata.test.ts
  yarn-audit-known-issues
  yarn.lock
Labels: add-or-update, ns:cui, prd:cui, rel:cui-ra-pr-83
