Repository hmcts/cui-ra, pull requests merged in 2023-07, with the labels that each got.

#120 C UI ra 69
  .yarn/install-state.gz
  src/main/modules/nunjucks/index.ts
  src/main/resources/translation/cy/services/PFL/contact.json
  src/main/resources/translation/cy/services/PFL/header.json
  src/main/resources/translation/en.json
  src/main/resources/translation/en/common.json
  src/main/resources/translation/en/default/contact.json
  src/main/resources/translation/en/services/PFL/contact.json
  src/main/resources/translation/en/services/PFL/header.json
  src/main/views/error.njk
  src/main/views/home.njk
  src/main/views/not-found.njk
  src/main/views/template.njk
  yarn-audit-known-issues
Labels: ns:cui, prd:cui, rel:cui-ra-pr-120

#121 C UI ra 68
  .yarn/install-state.gz
  src/main/interfaces/dataManager.ts
  src/main/interfaces/index.ts
  src/main/interfaces/payload.ts
  src/main/managers/dataManager.ts
  src/main/managers/existingFlagsManager.ts
  src/main/managers/index.ts
  src/main/managers/newFlagsManager.ts
  src/main/processors/dataProcessor.ts
  src/main/processors/index.ts
  src/main/utilities/dateTime.ts
  src/main/utilities/index.ts
  src/test/unit/data/data-processor-results.json
  src/test/unit/data/flags-payload.json
  src/test/unit/data/flags.json
  src/test/unit/tests/managers/dataManager.test.ts
  src/test/unit/tests/managers/existingFlagsManager.test.ts
  src/test/unit/tests/managers/newFlagsManager.test.ts
  src/test/unit/tests/processors/dataProcessor.test.ts
  src/test/unit/tests/sample.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-121

#126 C UI ra 84
  .yarn/install-state.gz
  src/main/app.ts
  src/main/modules/translation/index.ts
  src/main/resources/translation/en/common.json
  src/main/resources/translation/en/errors/404.json
  src/main/resources/translation/en/errors/500.json
  src/main/resources/translation/en/services/PFL/contact.json
  src/main/views/error/404.njk
  src/main/views/error/500.njk
Labels: ns:cui, prd:cui, rel:cui-ra-pr-126

#127 C UI ra 69
  .yarn/install-state.gz
  src/main/assets/scss/header.scss
  src/main/assets/scss/main.scss
  src/main/resources/translation/en/common.json
  src/main/resources/translation/en/services/PFL/header.json
  src/main/views/template.njk
Labels: ns:cui, prd:cui, rel:cui-ra-pr-127

#130 C UI ra 37
  .yarn/install-state.gz
  src/main/resources/translation/en/common.json
  src/main/views/intro.njk
  src/main/views/not-found.njk
Labels: ns:cui, prd:cui, rel:cui-ra-pr-130

#131 Amended block to pull in contact section
  src/main/views/intro.njk
Labels: ns:cui, prd:cui, rel:cui-ra-pr-131

#132 C UI ra 36
  src/main/assets/scss/main.scss
  src/main/assets/scss/override.scss
  src/main/modules/nunjucks/index.ts
  src/main/resources/translation/en/common.json
  src/main/resources/translation/en/services/PFL/contact.json
  src/main/views/overview.njk
Labels: ns:cui, prd:cui, rel:cui-ra-pr-132

#135 middlewares and unit testing
  .yarn/install-state.gz
  src/main/app.ts
  src/main/controllers/apiController.ts
  src/main/controllers/index.ts
  src/main/middlewares/index.ts
  src/main/middlewares/requireIdam.ts
  src/main/middlewares/serviceAuthentication.ts
  src/main/modules/awilix/index.ts
  src/main/routes.ts
  src/main/routes/home.ts
  src/main/routes/info.ts
  src/test/unit/mocks/response.ts
  src/test/unit/tests/controllers/apiController.test.ts
  src/test/unit/tests/middlewares/requireIdam.test.ts
  src/test/unit/tests/middlewares/serviceAuthentication.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-135
