Repository hmcts/cui-ra, pull requests merged in 2023-09, with the labels that each got.

#225 cui-ra 22
  .pnp.cjs
  .yarn/cache/ajv-errors-npm-3.0.0-cbd6be5a29-f3d1610a10.zip
  .yarn/install-state.gz
  package.json
  src/main/builders/formBuilder.ts
  src/main/constants/common.ts
  src/main/constants/index.ts
  src/main/controllers/formController.ts
  src/main/demo/data/data-processor-results.json
  src/main/modules/nunjucks/index.ts
  src/main/processors/flagProcessor.ts
  src/main/processors/formProcessor.ts
  src/main/resources/translation/en/common.json
  src/main/resources/translation/en/flags.json
  src/main/schemas/formdata.ts
  src/main/schemas/index.ts
  src/main/validators/formValidator.ts
  src/main/validators/index.ts
  src/main/views/forms/base.njk
  src/main/views/forms/checkbox-group.njk
  src/test/unit/data/data-processor-results.json
  src/test/unit/tests/controllers/formController.test.ts
  src/test/unit/tests/processors/formProcessor.test.ts
  src/test/unit/tests/validators/formValidator.test.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:cui, prd:cui, rel:cui-ra-pr-225

#226 updated text
  src/main/resources/translation/en/common.json
Labels: ns:cui, prd:cui, rel:cui-ra-pr-226

#227 C UI ra 145
  src/main/resources/translation/en/common.json
Labels: ns:cui, prd:cui, rel:cui-ra-pr-227

#230 alphabetical sorting
  .yarn/install-state.gz
  src/main/builders/formBuilder.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-230

#233 C UI ra 32
  .yarn/install-state.gz
  src/main/views/forms/base.njk
  src/main/views/forms/checkbox-group.njk
  src/main/views/forms/radio-group.njk
  src/main/views/forms/type-ahead.njk
Labels: ns:cui, prd:cui, rel:cui-ra-pr-233

#237 amended flag resource properties to be consistent with confluence and…
  .yarn/install-state.gz
  src/main/resources/translation/cy/flags.json
  src/main/resources/translation/en/flags.json
  src/main/views/forms/base.njk
Labels: ns:cui, prd:cui, rel:cui-ra-pr-237

#239 Demo footer link content
  .yarn/install-state.gz
  src/main/constants/route.ts
  src/main/controllers/demoController.ts
  src/main/controllers/homeController.ts
  src/main/resources/translation/en/services/PFL/contact.json
  src/main/routes.ts
  src/main/views/accessibility-statement.njk
  src/main/views/cookies.njk
  src/main/views/privacy-policy.njk
  src/main/views/template.njk
  src/main/views/terms-and-conditions.njk
  src/test/unit/tests/controllers/homeController.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-239

#245 C UI ra 32
  .yarn/install-state.gz
  src/main/demo/data/data-processor-results.json
  src/main/middlewares/requireIdam.ts
  src/main/middlewares/serviceAuthentication.ts
  src/main/services/refdata.ts
  src/test/unit/data/data-processor-results.json
  src/test/unit/data/flags.json
Labels: ns:cui, prd:cui, rel:cui-ra-pr-245

#254 C UI ra 32
  .yarn/install-state.gz
  src/main/builders/index.ts
  src/main/builders/payloadBuilder.ts
  src/main/constants/route.ts
  src/main/controllers/apiController.ts
  src/main/controllers/dataController.ts
  src/main/controllers/demoController.ts
  src/main/controllers/reviewController.ts
  src/main/interfaces/redisClient.ts
  src/main/routes.ts
  src/main/services/fileStorage.ts
  src/main/services/redis.ts
  src/main/views/review.njk
  src/test/unit/data/outbound-payload.json
  src/test/unit/mocks/redis.ts
  src/test/unit/tests/builders/payloadBuilder.test.ts
  src/test/unit/tests/controllers/reviewController.test.ts
  src/test/unit/tests/services/fileStorage.test.ts
  src/test/unit/tests/services/redis.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-254

#256 s2s fix added bearer
  .yarn/install-state.gz
  src/main/services/refdata.ts
  src/main/services/s2s.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-256

#257 prevent user with no session to access site
  .yarn/install-state.gz
  src/main/constants/route.ts
  src/main/controllers/dataController.ts
  src/main/controllers/demoController.ts
  src/main/managers/newFlagsManager.ts
  src/main/middlewares/initSession.ts
  src/main/routes.ts
  src/main/types/index.d.ts
  src/test/unit/mocks/refData.ts
  src/test/unit/tests/controllers/dataController.test.ts
  src/test/unit/tests/managers/newFlagsManager.test.ts
  src/test/unit/tests/middlewares/initSession.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-257

#258 C UI ra 24
  .yarn/install-state.gz
  src/main/app.ts
  src/main/constants/route.ts
  src/main/controllers/demoController.ts
  src/main/middlewares/history.ts
  src/main/middlewares/index.ts
  src/main/routes.ts
  src/main/types/index.d.ts
  src/main/views/dynamic-form.njk
  src/main/views/forms/base.njk
  src/main/views/forms/checkbox-group.njk
  src/main/views/forms/radio-group.njk
  src/main/views/forms/type-ahead.njk
  src/main/views/intro.njk
  src/main/views/overview.njk
  src/main/views/review.njk
  src/test/unit/tests/middlewares/history.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-258

#259 redis ttl and api fix
  .yarn/install-state.gz
  src/main/modules/session/index.ts
  src/main/services/redis.ts
  src/main/services/s2s.ts
  src/test/unit/tests/services/redis.test.ts
  src/test/unit/tests/services/s2s.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-259

#260 C UI ra 44
  .yarn/install-state.gz
  src/main/routes.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-260

#261 updated refdata api
  src/main/routes.ts
  src/main/services/refdata.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-261

#267 C UI ra language
  .yarn/install-state.gz
  src/main/builders/formBuilder.ts
  src/main/constants/route.ts
  src/main/controllers/dataController.ts
  src/main/controllers/demoController.ts
  src/main/controllers/formController.ts
  src/main/controllers/reviewController.ts
  src/main/models/inboundPayload.ts
  src/main/modules/csrf/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/routes.ts
  src/main/schemas/InboundPayload.ts
  src/main/types/index.d.ts
  src/main/views/demo.njk
  src/main/views/forms/base.njk
  src/main/views/forms/checkbox-group.njk
  src/main/views/forms/radio-group.njk
  src/main/views/forms/type-ahead.njk
  src/test/unit/tests/controllers/demoController.test.ts
  src/test/unit/tests/controllers/reviewController.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-267

#269 C UI ra 44
  .yarn/install-state.gz
  src/main/builders/payloadBuilder.ts
  src/main/constants/actions.ts
  src/main/constants/index.ts
  src/main/constants/route.ts
  src/main/controllers/reviewController.ts
  src/main/models/inboundPayload.ts
  src/main/resources/translation/cy/common.json
  src/main/resources/translation/en/common.json
  src/main/routes.ts
  src/main/views/dynamic-form.njk
  src/main/views/forms/base.njk
  src/main/views/intro.njk
  src/main/views/review.njk
  src/test/unit/tests/builders/payloadBuilder.test.ts
  src/test/unit/tests/controllers/reviewController.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-269

#270 fix api get route
  src/main/constants/route.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-270

#271 pass change query and continue it forward
  src/main/controllers/formController.ts
  src/main/views/review.njk
  src/test/unit/tests/controllers/formController.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-271

#272 C UI ra 44
  .yarn/install-state.gz
  src/main/constants/route.ts
  src/main/controllers/formController.ts
  src/main/controllers/homeController.ts
  src/main/controllers/reviewController.ts
  src/main/routes.ts
  src/main/views/forms/base.njk
  src/main/views/template.njk
  src/test/unit/mocks/response.ts
  src/test/unit/tests/controllers/formController.test.ts
  src/test/unit/tests/controllers/homeController.test.ts
  src/test/unit/tests/controllers/reviewController.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-272

#275 C UI ra 126
  .yarn/install-state.gz
  src/main/controllers/formController.ts
  src/main/managers/newFlagsManager.ts
  src/main/views/review.njk
  src/test/unit/tests/controllers/formController.test.ts
  src/test/unit/tests/managers/newFlagsManager.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-275

#277 sorting refdata alphabetically
  .yarn/install-state.gz
  src/main/controllers/dataController.ts
  src/main/controllers/demoController.ts
  src/main/demo/data/data-processor-results-welsh.json
  src/main/demo/data/data-processor-results.json
  src/main/interfaces/flagProcessor.ts
  src/main/processors/flagProcessor.ts
  src/test/unit/data/data-processor-results-welsh.json
  src/test/unit/data/data-processor-results.json
  src/test/unit/mocks/flagProcessor.ts
  src/test/unit/tests/processors/flagProcessor.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-277

#278 output corrolation id
  src/main/builders/payloadBuilder.ts
  src/main/controllers/dataController.ts
  src/main/models/inboundPayload.ts
  src/main/types/index.d.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-278

#279 Update renovate.json
  .github/renovate.json
Labels: ns:cui, prd:cui, rel:cui-ra-pr-279

#281 Updated translation prop names from snake case to camel case
  .yarn/install-state.gz
  src/main/resources/translation/cy/common.json
  src/main/resources/translation/en/common.json
  src/main/resources/translation/en/errors/404.json
  src/main/resources/translation/en/errors/500.json
  src/main/resources/translation/en/services/PFL/header.json
  src/main/views/dynamic-form.njk
  src/main/views/error/404.njk
  src/main/views/error/500.njk
  src/main/views/forms/base.njk
  src/main/views/forms/checkbox-group.njk
  src/main/views/forms/radio-group.njk
  src/main/views/forms/type-ahead.njk
  src/main/views/intro.njk
  src/main/views/overview.njk
  src/main/views/review.njk
  src/main/views/template.njk
  yarn-audit-known-issues
Labels: ns:cui, prd:cui, rel:cui-ra-pr-281

#282 error handling
  .yarn/install-state.gz
  src/main/controllers/dataController.ts
  src/main/controllers/demoController.ts
  src/main/controllers/formController.ts
  src/main/controllers/homeController.ts
  src/main/controllers/reviewController.ts
  src/test/unit/tests/controllers/dataController.test.ts
  src/test/unit/tests/controllers/demoController.test.ts
  src/test/unit/tests/controllers/formController.test.ts
  src/test/unit/tests/controllers/homeController.test.ts
  src/test/unit/tests/controllers/reviewController.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-282

#285 csrf protection
  src/main/app.ts
  src/main/modules/csrf/index.ts
  src/main/modules/index.ts
  src/main/views/demo.njk
  src/main/views/forms/base.njk
  src/main/views/review.njk
Labels: ns:cui, prd:cui, rel:cui-ra-pr-285

#286 C UI ra js
  .yarn/install-state.gz
  charts/cui-ra/Chart.yaml
  charts/cui-ra/values.aat.template.yaml
  charts/cui-ra/values.yaml
  config/custom-environment-variables.json
  config/default.json
  config/development.json
  src/main/assets/js/index.ts
  src/main/routes.ts
  src/main/views/forms/type-ahead.njk
Labels: ns:cui, prd:cui, rel:cui-ra-pr-286

#288 C UI ra 190
  .yarn/install-state.gz
  src/main/resources/translation/cy/common.json
  src/main/resources/translation/en/common.json
  src/main/resources/translation/en/flags.json
  src/main/views/forms/checkbox-group.njk
  src/main/views/review.njk
Labels: ns:cui, prd:cui, rel:cui-ra-pr-288

#293 C UI ra 134
  .yarn/install-state.gz
  src/main/builders/formBuilder.ts
  src/main/controllers/demoController.ts
  src/main/controllers/reviewController.ts
  src/main/resources/translation/cy/common.json
  src/main/resources/translation/en/common.json
  src/main/utilities/customSort.ts
  src/main/utilities/index.ts
  src/main/views/forms/base.njk
  src/main/views/forms/radio-group.njk
  src/main/views/forms/type-ahead.njk
  src/main/views/review.njk
  src/test/unit/tests/utilities/customSort.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-293

#292 C UI ra a11 y
  .pnp.cjs
  .yarn/cache/@puppeteer-browsers-npm-1.7.1-a197dcc835-fb7cf7773a.zip
  .yarn/cache/@tootallnate-quickjs-emscripten-npm-0.23.0-a889ea7aeb-c350a2947f.zip
  .yarn/cache/agent-base-npm-7.1.0-4b12ba5111-f7828f9914.zip
  .yarn/cache/ast-types-npm-0.13.4-69f7e68df8-5a51f7b705.zip
  .yarn/cache/b4a-npm-1.6.4-080bcba845-81b086f9af.zip
  .yarn/cache/basic-ftp-npm-5.0.3-95a5b33162-8b04e88eb8.zip
  .yarn/cache/chromium-bidi-npm-0.4.28-d14ac319b4-d8ac0aefcf.zip
  .yarn/cache/cliui-npm-8.0.1-3b029092cf-79648b3b00.zip
  .yarn/cache/cosmiconfig-npm-8.3.6-a5566e2779-dc339ebea4.zip
  .yarn/cache/cross-fetch-npm-4.0.0-9c67668db4-ecca4f37ff.zip
  .yarn/cache/data-uri-to-buffer-npm-5.0.1-a40e5ac026-10958f89c0.zip
  .yarn/cache/degenerator-npm-5.0.1-97c678cdaf-a64fa39cdf.zip
  .yarn/cache/devtools-protocol-npm-0.0.1179426-3c128037ae-38a091bde4.zip
  .yarn/cache/escodegen-npm-2.1.0-e0bf940745-096696407e.zip
  .yarn/cache/fast-fifo-npm-1.3.2-391cc25df4-6bfcba3e4d.zip
  .yarn/cache/get-uri-npm-6.0.1-d4f0bb7365-a8aec70e1c.zip
  .yarn/cache/http-proxy-agent-npm-7.0.0-106a57cc8c-48d4fac997.zip
  .yarn/cache/https-proxy-agent-npm-7.0.2-83ea6a5d42-088969a0dd.zip
  .yarn/cache/ip-npm-1.1.8-abea558b72-a2ade53eb3.zip
  .yarn/cache/lru-cache-npm-7.18.3-e68be5b11c-e550d77238.zip
  .yarn/cache/mitt-npm-3.0.1-ce290ffa77-b55a489ac9.zip
  .yarn/cache/netmask-npm-2.0.2-2299510a4d-c65cb8d3f7.zip
  .yarn/cache/node-fetch-npm-2.7.0-587d57004e-d76d2f5edb.zip
  .yarn/cache/pac-proxy-agent-npm-7.0.1-8d7216fff5-3d4aa48ec1.zip
  .yarn/cache/pac-resolver-npm-7.0.0-904b294260-fa3a898c09.zip
  .yarn/cache/proxy-agent-npm-6.3.1-b14461a822-31030da419.zip
  .yarn/cache/puppeteer-core-npm-21.3.6-5e2ffe6643-18f85781d0.zip
  .yarn/cache/puppeteer-npm-21.3.6-1cb044f6d8-781dd1061e.zip
  .yarn/cache/queue-tick-npm-1.0.1-10bd6eaf3d-57c3292814.zip
  .yarn/cache/socks-npm-2.7.1-17f2b53052-259d9e3e8e.zip
  .yarn/cache/socks-proxy-agent-npm-8.0.2-df165543cf-4fb165df08.zip
  .yarn/cache/streamx-npm-2.15.1-d5dbdeeb03-6f2b4fed68.zip
  .yarn/cache/tar-fs-npm-3.0.4-fa3da2e321-dcf4054f9e.zip
  .yarn/cache/tar-stream-npm-3.1.6-ce3ac17e49-f3627f9185.zip
  .yarn/cache/tslib-npm-2.6.2-4fc8c068d9-329ea56123.zip
  .yarn/cache/urlpattern-polyfill-npm-9.0.0-b3c823788f-d3658b78a1.zip
  .yarn/cache/ws-npm-8.14.2-b339ac47a2-3ca0dad26e.zip
  .yarn/cache/yargs-npm-17.7.1-0758ec0e50-3d8a43c336.zip
  .yarn/install-state.gz
  config/test.json
  demo.png
  package.json
  src/main/app.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/session/index.ts
  src/main/views/demo.njk
  src/main/views/template.njk
  src/test/a11y/a11y.ts
  src/test/a11y/dummy-test.ts
  yarn.lock
Labels: ns:cui, prd:cui, rel:cui-ra-pr-292
