Repository hmcts/cui-ra, pull requests merged in 2023-12, with the labels that each got.

#393 it has been decided to keep the full iso datetime string
  .yarn/install-state.gz
  src/main/managers/dataManager.ts
  src/main/utilities/dateTime.ts
  src/test/unit/tests/utilities/dateTime.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-393

#397 enable demo for preview chart
  .yarn/install-state.gz
  charts/cui-ra/values.preview.template.yaml
Labels: ns:cui, prd:cui, rel:cui-ra-pr-397

#398 enabled tests and set local url
  .github/workflows/checks.yml
  config/default.json
  config/production.json
  src/test/config.ts
  src/test/functional/features/new-Journey.feature
  src/test/steps/commonsteps.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-398

#401 added other back but removed chair
  src/main/demo/data/data-processor-results-welsh.json
  src/main/demo/data/data-processor-results.json
  src/main/resources/configs/services/ABA5.json
  src/test/steps/commonsteps.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-401

#406 C UI ra docker
  .yarn/install-state.gz
  README.md
  charts/cui-ra/Chart.yaml
  charts/cui-ra/values.yaml
  config/custom-environment-variables.json
  config/default.json
  config/development.json
  config/test.json
  docker-compose.yml
  nginx/nginx.conf
  src/main/controllers/demoController.ts
  src/main/modules/session/index.ts
  src/main/resources/translation/cy/common.json
  src/main/resources/translation/en/common.json
  src/main/services/redis.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-406

#409 DTSPO-15909 - migrated Application Insights
  infrastructure/main.tf
Labels: add-or-update, ns:cui, prd:cui, rel:cui-ra-pr-409
