Repository hmcts/cui-ra, pull requests merged in 2023-10, with the labels that each got.

#296 C UI ra 181
  .yarn/install-state.gz
  src/main/demo/data/demo-payload.json
  src/main/views/overview.njk
  src/main/views/review.njk
Labels: ns:cui, prd:cui, rel:cui-ra-pr-296

#299 all pa11y test now return no errors
  .yarn/install-state.gz
  sonar-project.properties
  src/main/assets/js/index.ts
  src/main/views/components/accessible-autocomplete/template.njk
  src/main/views/forms/base.njk
  src/main/views/forms/checkbox-group.njk
  src/main/views/forms/radio-group.njk
  src/main/views/forms/type-ahead.njk
  src/test/a11y/a11y.ts
  yarn-audit-known-issues
Labels: ns:cui, prd:cui, rel:cui-ra-pr-299

#303 added new resource item called command and display it in the view
  .yarn/install-state.gz
  src/main/resources/translation/cy/common.json
  src/main/resources/translation/cy/flags.json
  src/main/resources/translation/en/common.json
  src/main/resources/translation/en/flags.json
  src/main/views/forms/checkbox-group.njk
  src/main/views/template.njk
Labels: ns:cui, prd:cui, rel:cui-ra-pr-303

#304 added labelledby on textarea input
  src/main/views/forms/checkbox-group.njk
Labels: ns:cui, prd:cui, rel:cui-ra-pr-304

#305 fixed callbackUrl and logoutUrl schmea
  src/main/schemas/InboundPayload.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-305

#306 changed required
  src/main/schemas/InboundPayload.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-306

#307 bug find master code
  src/main/controllers/dataController.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-307

#311 on invalid empty data create temp data and clear infomation
  .yarn/install-state.gz
  src/main/controllers/formController.ts
  src/main/schemas/formdata.ts
  src/test/unit/tests/controllers/formController.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-311

#313 Migrate redis cache to Basic sku in non-prod env
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:cui, prd:cui, destroy, rel:cui-ra-pr-313

#317 Update azurerm version in state.tf
  infrastructure/state.tf
Labels: add-or-update, ns:cui, prd:cui, rel:cui-ra-pr-317

#315 C UI ra config
  src/main/demo/data/data-processor-results-welsh.json
  src/main/demo/data/data-processor-results.json
  src/main/managers/newFlagsManager.ts
  src/test/unit/tests/managers/newFlagsManager.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-315

#318 changed if statement to and instead of or
  .yarn/install-state.gz
  charts/cui-ra/Chart.yaml
  src/main/processors/formProcessor.ts
  src/test/unit/tests/processors/formProcessor.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-318

#320 revert node version in charts
  charts/cui-ra/Chart.yaml
Labels: ns:cui, prd:cui, rel:cui-ra-pr-320

#321 added translations for RA0007
  src/main/resources/translation/cy/flags.json
  src/main/resources/translation/en/flags.json
  src/main/views/forms/checkbox-group.njk
Labels: ns:cui, prd:cui, rel:cui-ra-pr-321

#325 C UI ra 200
  .yarn/install-state.gz
  src/main/resources/translation/cy/flags.json
  src/main/views/forms/base.njk
Labels: ns:cui, prd:cui, rel:cui-ra-pr-325

#328 maxAge 30 min
  config/development.json
Labels: ns:cui, prd:cui, rel:cui-ra-pr-328

#332 check if details exist before setting
  src/main/controllers/dataController.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-332

#333 update chart version
  charts/cui-ra/Chart.yaml
Labels: ns:cui, prd:cui, rel:cui-ra-pr-333

#334 add no cache to nunjucks
  .yarn/install-state.gz
  src/main/modules/nunjucks/index.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-334

#337 revert infrastructue
  infrastructure/main.tf
Labels: add-or-update, ns:cui, prd:cui, rel:cui-ra-pr-337

#338 change chart version
  charts/cui-ra/Chart.yaml
Labels: ns:cui, prd:cui, rel:cui-ra-pr-338

#344 C UI ra 207
  .yarn/install-state.gz
  src/main/builders/payloadBuilder.ts
  src/main/constants/errorMessages.ts
  src/main/controllers/dataController.ts
  src/main/controllers/demoController.ts
  src/main/controllers/reviewController.ts
  src/main/demo/data/data-processor-results-welsh.json
  src/main/demo/data/data-processor-results.json
  src/main/interfaces/dataManager.ts
  src/main/interfaces/existingFlagProcessor.ts
  src/main/interfaces/index.ts
  src/main/managers/existingFlagsManager.ts
  src/main/modules/awilix/index.ts
  src/main/processors/existingflagProcessor.ts
  src/main/processors/index.ts
  src/test/unit/data/existing-processor-results.json
  src/test/unit/mocks/existingFlagProcessor.ts
  src/test/unit/mocks/index.ts
  src/test/unit/tests/builders/payloadBuilder.test.ts
  src/test/unit/tests/controllers/dataController.test.ts
  src/test/unit/tests/controllers/demoController.test.ts
  src/test/unit/tests/controllers/homeController.test.ts
  src/test/unit/tests/controllers/reviewController.test.ts
  src/test/unit/tests/managers/existingFlagsManager.test.ts
  src/test/unit/tests/processors/existingFlagProcessor.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-344

#347 added script to grow and shrink textarea
  .yarn/install-state.gz
  src/main/assets/js/index.ts
  src/main/assets/scss/main.scss
Labels: ns:cui, prd:cui, rel:cui-ra-pr-347

#349 C UI ra 210
  src/main/resources/translation/cy/common.json
  src/main/resources/translation/en/common.json
  src/main/views/forms/base.njk
  src/main/views/review.njk
  src/main/views/template.njk
Labels: ns:cui, prd:cui, rel:cui-ra-pr-349

#350 aria on feedback
  src/main/views/review.njk
  src/main/views/template.njk
Labels: ns:cui, prd:cui, rel:cui-ra-pr-350

#352 link color
  src/main/resources/translation/en/services/PFL/contact.json
Labels: ns:cui, prd:cui, rel:cui-ra-pr-352
