Repository hmcts/cui-ra, pull requests merged in 2024-02, with the labels that each got.

#470 CUIRA-179 load different env urls for footer links
  charts/cui-ra/Chart.yaml
  charts/cui-ra/values.yaml
  src/main/app.ts
  src/main/assets/manifest.json
  src/main/builders/payloadBuilder.ts
  src/main/controllers/reviewController.ts
  src/main/middlewares/requireIdam.ts
  src/main/modules/helmet/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/resources/translation/cy/services/PFL/footer.json
  src/main/resources/translation/en/services/PFL/footer.json
  src/main/views/template.njk
  src/test/unit/tests/controllers/reviewController.test.ts
  webpack/govukFrontend.js
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-470

#473 CUIRA-238 correctly pass information for substitution
  src/main/views/forms/checkbox-group.njk
  src/main/views/forms/radio-group.njk
  src/main/views/forms/type-ahead.njk
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-473

#475 CUIRA-260 clear session history on start, do not store home in history
  src/main/controllers/dataController.ts
  src/main/routes.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-475

#479 CUIRA-179 rename PFL to ABA5
  src/main/controllers/dataController.ts
  src/main/controllers/demoController.ts
  src/main/resources/translation/cy/services/PFL/flags.json
  src/main/resources/translation/cy/services/PFL/footer.json
  src/main/resources/translation/en/services/ABA5/contact.json
  src/main/resources/translation/en/services/ABA5/flags.json
  src/main/resources/translation/en/services/ABA5/footer.json
  src/main/resources/translation/en/services/ABA5/header.json
  src/main/resources/translation/en/services/PFL/flags.json
  src/main/resources/translation/en/services/PFL/header.json
Labels: ns:cui, prd:cui, rel:cui-ra-pr-479

#487 CUIRA-266 suppressing CVE
  yarn-audit-known-issues
Labels: ns:cui, prd:cui, rel:cui-ra-pr-487

#488 CUIRA-265 Changing status Not Approved to Not approved
  src/main/constants/status.ts
  src/main/demo/data/demo-payload.json
  src/main/resources/translation/en/common.json
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-488

#491 CUIRA-179 make preview env to be preview
  .pnp.cjs
  charts/cui-ra/values.preview.template.yaml
  package.json
  src/main/server.ts
  yarn.lock
Labels: ns:cui, prd:cui, rel:cui-ra-pr-491

#495 CUIRA-261 create app insights connection string
  infrastructure/main.tf
Labels: add-or-update, ns:cui, prd:cui, rel:cui-ra-pr-495

#496 Handpicked updates that should be safe to update
  .pnp.cjs
  .yarn/cache/@hmcts-nodejs-healthcheck-npm-1.8.3-0b01c623ac-76f87a5a67.zip
  .yarn/cache/@sideway-address-npm-4.1.4-32f94bc9f5-b9fca2a93a.zip
  .yarn/cache/check-error-npm-1.0.2-00c540c6e9-d9d1065044.zip
  .yarn/cache/dezalgo-npm-1.0.3-e2bc978ebd-8b26238db9.zip
  .yarn/cache/formidable-npm-2.0.1-b18227215c-b35445444e.zip
  .yarn/cache/get-func-name-npm-2.0.0-afbf363765-8d82e69f3e.zip
  .yarn/cache/superagent-npm-7.1.6-8f8391ba79-b733168360.zip
  package.json
  yarn.lock
Labels: ns:cui, prd:cui, rel:cui-ra-pr-496

#497 install playwright before functional tests
  Jenkinsfile_CNP
Labels: ns:cui, prd:cui, rel:cui-ra-pr-497

#498 CUIRA-264 escapingHTMLTags
  .pnp.cjs
  package.json
  src/main/app.ts
  src/main/middlewares/index.ts
  src/main/middlewares/sanitizeRequestBody.ts
  src/main/processors/formProcessor.ts
  src/test/unit/tests/middlewares/sanitizeRequestBody.test.ts
  yarn.lock
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-498

#501 Enable fortify scan
  Jenkinsfile_nightly
  package.json
  src/test/java/.gitignore
  src/test/java/build.gradle
  src/test/java/config/fortify-client.properties
  src/test/java/gradle/wrapper/gradle-wrapper.jar
  src/test/java/gradle/wrapper/gradle-wrapper.properties
  src/test/java/gradlew
  src/test/java/gradlew.bat
  src/test/java/settings.gradle
Labels: ns:cui, prd:cui, rel:cui-ra-pr-501

#492 CUIRA-239 replace tables with lists on review page
  src/main/views/review.njk
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-492

#502 CUIRA-271 fix typo
  Jenkinsfile_nightly
Labels: ns:cui, prd:cui, rel:cui-ra-pr-502

#494 CUIRA-261 replace appinsights instrumentation key with connection string
  charts/cui-ra/Chart.yaml
  charts/cui-ra/values.yaml
  config/default.json
  infrastructure/main.tf
  src/main/modules/appinsights/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/processors/flagProcessor.ts
Labels: ns:cui, prd:cui, destroy, enable_keep_helm, rel:cui-ra-pr-494

#504 CUIRA-271 update permissions policy
  Jenkinsfile_nightly
  src/main/app.ts
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-504
