Repository hmcts/cui-ra, pull requests merged in 2024-04, with the labels that each got.

#549 CUIRA-298 whitelist prl service
  charts/cui-ra/Chart.yaml
  charts/cui-ra/values.yaml
  config/default.json
Labels: ns:cui, prd:cui, rel:cui-ra-pr-549

#554 update js hash
  audit.json
Labels: ns:cui, prd:cui, rel:cui-ra-pr-554

#556 Error sorting and unit test with redis unit test fix
  .pnp.cjs
  package.json
  src/main/builders/formBuilder.ts
  src/main/utilities/errorSort.ts
  src/main/utilities/index.ts
  src/test/unit/mocks/redis.ts
  src/test/unit/tests/services/redis.test.ts
  src/test/unit/tests/utilities/errorSort.test.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:cui, prd:cui, rel:cui-ra-pr-556

#561 added unit tests for form builder
  .pnp.cjs
  package.json
  src/test/unit/tests/builders/formBuilder.test.ts
  yarn.lock
Labels: ns:cui, prd:cui, rel:cui-ra-pr-561

#563 formbuilder should now be more maintainable
  src/main/builders/formBuilder.ts
  src/main/constants/errorMessages.ts
  src/test/unit/tests/builders/formBuilder.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-563

#560 optimised form validator
  src/main/validators/formValidator.ts
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-560

#565 Update yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:cui, prd:cui, rel:cui-ra-pr-565

#566 remove playwright cache
  Jenkinsfile_CNP
Labels: ns:cui, prd:cui, rel:cui-ra-pr-566

#559 run full functional tests in nightly
  Jenkinsfile_nightly
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-559

#568 Cuira 334
  src/main/constants/errorMessages.ts
  src/main/controllers/dataController.ts
  src/main/errors/dataController.ts
  src/main/errors/index.ts
  src/main/errors/s2s.ts
  src/main/services/s2s.ts
  src/test/unit/tests/controllers/dataController.test.ts
  src/test/unit/tests/services/s2s.test.ts
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-568

#572 use wild cards in zap proxy audit ignore file
  audit.json
Labels: ns:cui, prd:cui, rel:cui-ra-pr-572

#573 update audit and install playwright before fully functional
  audit.json
  package.json
Labels: ns:cui, prd:cui, rel:cui-ra-pr-573

#574 Cuira vul 5633
  .eslintignore
  .pnp.cjs
  .yarn/cache/@babel-compat-data-npm-7.22.9-f9e02d51b9-bed77d9044.zip
  .yarn/cache/@babel-helper-compilation-targets-npm-7.22.15-7aac9e71ad-ce85196769.zip
  .yarn/cache/@babel-helper-member-expression-to-functions-npm-7.22.15-f86d38ada1-c7c5d01c40.zip
  .yarn/cache/@babel-helper-validator-option-npm-7.22.15-29aa330042-68da52b1e1.zip
  .yarn/cache/@eslint-community-regexpp-npm-4.5.1-bf72922237-6d901166d6.zip
  .yarn/cache/@hmcts-info-provider-npm-1.1.0-ff33fd10d2-e1ddca0e05.zip
  .yarn/cache/@types-helmet-npm-4.0.0-48d8baa6ce-ded60d8d99.zip
  .yarn/cache/@webassemblyjs-ast-npm-1.11.5-ad883e230f-7df16d8d43.zip
  .yarn/cache/@webassemblyjs-floating-point-hex-parser-npm-1.11.5-01ff4bf952-a6f35e3035.zip
  .yarn/cache/@webassemblyjs-helper-api-error-npm-1.11.5-553acf3c94-717a6ffb32.zip
  .yarn/cache/@webassemblyjs-helper-buffer-npm-1.11.5-76356c5b6d-2c0925b1c3.zip
  .yarn/cache/@webassemblyjs-helper-numbers-npm-1.11.5-efa2500e8e-49c8bbf561.zip
  .yarn/cache/@webassemblyjs-helper-wasm-bytecode-npm-1.11.5-2f1be836c6-4e868de925.zip
  .yarn/cache/@webassemblyjs-helper-wasm-section-npm-1.11.5-b74ded6c5d-1752d7e0db.zip
  .yarn/cache/@webassemblyjs-ieee754-npm-1.11.5-42a1b795b4-68a855a3e3.zip
  .yarn/cache/@webassemblyjs-leb128-npm-1.11.5-7e82c71f81-555314708b.zip
  .yarn/cache/@webassemblyjs-utf8-npm-1.11.5-775c246fbf-d8f67a5650.zip
  .yarn/cache/@webassemblyjs-wasm-edit-npm-1.11.5-9643f15610-790142a1e2.zip
  .yarn/cache/@webassemblyjs-wasm-gen-npm-1.11.5-a3a569938d-0122df4e5c.zip
  .yarn/cache/@webassemblyjs-wasm-opt-npm-1.11.5-efd2b45433-f9416b0dec.zip
  .yarn/cache/@webassemblyjs-wasm-parser-npm-1.11.5-c3794b38b2-094b3df075.zip
  .yarn/cache/@webassemblyjs-wast-printer-npm-1.11.5-b5f768e688-c2995224c5.zip
  .yarn/cache/accessible-autocomplete-npm-2.0.4-307dcafc0e-e1eeff2785.zip
  .yarn/cache/acorn-npm-8.9.0-4ebbf0f638-25dfb94952.zip
  .yarn/cache/chokidar-npm-3.3.1-98709e3b9f-84b01c2e75.zip
  .yarn/cache/copy-webpack-plugin-npm-9.1.0-ea49123db5-06cb4fb6fc.zip
  .yarn/cache/cross-fetch-npm-4.0.0-9c67668db4-ecca4f37ff.zip
  .yarn/cache/doctrine-npm-3.0.0-c6f1615f04-fd7673ca77.zip
  .yarn/cache/enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip
  .yarn/cache/eslint-scope-npm-7.2.2-53cb0df8e8-ec97dbf5fb.zip
  .yarn/cache/espree-npm-9.6.0-8f679a5d0a-1287979510.zip
  .yarn/cache/espree-npm-9.6.1-a50722a5a9-eb8c149c7a.zip
  .yarn/cache/express-nunjucks-npm-3.1.1-89debd405a-f41928106d.zip
  .yarn/cache/file-entry-cache-npm-6.0.1-31965cf0af-f49701feaa.zip
  .yarn/cache/flat-cache-npm-3.0.4-ee77e5911e-4fdd10ecbc.zip
  .yarn/cache/flatted-npm-3.2.7-0da10b7c56-427633049d.zip
  .yarn/cache/formidable-npm-2.1.2-40ba18d67f-81c8e5d89f.zip
  .yarn/cache/fsevents-npm-2.1.3-091ef5a0af-b5ec0516b4.zip
  .yarn/cache/globals-npm-13.20.0-4565a722e7-ad1ecf914b.zip
  .yarn/cache/helmet-npm-7.0.0-13c1e96edf-3622b8b68b.zip
  .yarn/cache/ignore-npm-5.2.4-fbe6e989e5-3d4c309c60.zip
  .yarn/cache/ioredis-npm-5.3.2-58471071b1-9a23559133.zip
  .yarn/cache/nunjucks-async-loader-npm-2.1.2-9f5a24a6b6-6a68153352.zip
  .yarn/cache/preact-npm-8.5.3-20c7a48524-1a2d90816a.zip
  .yarn/cache/readdirp-npm-3.3.0-c98c003159-f8289b21d2.zip
  .yarn/cache/table-npm-6.8.1-83abb79e20-08249c7046.zip
  .yarn/cache/type-fest-npm-0.20.2-b36432617f-4fb3272df2.zip
  .yarn/cache/watchpack-npm-2.4.0-7ec4b9cc65-23d4bc5863.zip
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/releases/yarn-3.8.1.cjs
  eslint.config.js
  package.json
  yarn.lock
Labels: ns:cui, prd:cui, rel:cui-ra-pr-574
