Repository hmcts/cui-ra, pull requests merged in 2024-03, with the labels that each got.

#506 CUIRA-277 error messages on no fields selected
  src/main/resources/translation/cy/flags.json
  src/main/resources/translation/en/flags.json
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-506

#510 CUIRA-271 ignore failing files
  audit.json
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-510

#511 CUIRA-271 update audit json
  audit.json
Labels: ns:cui, prd:cui, rel:cui-ra-pr-511

#514 extract redis-host to property
  Jenkinsfile_CNP
  charts/cui-ra/Chart.yaml
  charts/cui-ra/values.yaml
  src/main/modules/properties-volume/index.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-514

#518 CUIRA-291 keep connection alive for 60sec
  src/main/modules/session/index.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-518

#526 Force newer puppeteer
  .pnp.cjs
  .yarn/cache/cosmiconfig-npm-8.2.0-9b42f8a44e-836d5d8efa.zip
  package.json
  yarn.lock
Labels: ns:cui, prd:cui, rel:cui-ra-pr-526

#524 CUIRA-292 show selected options in Welsh, if Welsh language is selected
  src/main/views/overview.njk
Labels: ns:cui, prd:cui, rel:cui-ra-pr-524

#522 CUIRA-276 update text under link to EASS
  src/main/resources/translation/cy/static/accessibility.json
  src/main/resources/translation/en/static/accessibility.json
Labels: ns:cui, prd:cui, rel:cui-ra-pr-522

#508 CUIRA-279 do not de-select parent on submitting empty form page
  package.json
  src/main/managers/newFlagsManager.ts
  src/main/resources/translation/en/flags.json
  src/test/functional/features/error-does-not-clear-parent.feature
  src/test/steps/commonsteps.ts
  src/test/unit/tests/managers/newFlagsManager.test.ts
  yarn.lock
Labels: add-or-update, ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-508

#525 Cuira 291
  src/main/modules/session/index.ts
Labels: add-or-update, ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-525

#528 Add ping in every minute
  src/main/modules/session/index.ts
  src/main/services/redis.ts
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-528

#532 CUIRA-281 enable spot instances
  charts/cui-ra/Chart.yaml
  charts/cui-ra/values.yaml
Labels: ns:cui, prd:cui, rel:cui-ra-pr-532

#530 CUIRA-269 replace table with list in overview page
  src/main/assets/scss/main.scss
  src/main/views/overview.njk
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-530

#535 Update css hash for zaproxy
  audit.json
Labels: ns:cui, prd:cui, rel:cui-ra-pr-535

#533 CUIRA-287 remove /health/ endpoint logging
  config/default.json
  src/main/modules/appinsights/index.ts
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-533

#517 CUIRA-283 show error page on error
  src/main/app.ts
  src/main/controllers/dataController.ts
  src/main/controllers/reviewController.ts
  src/main/modules/nunjucks/index.ts
  src/main/schemas/InboundPayload.ts
  src/main/views/webpack/css.njk
  src/test/unit/tests/controllers/dataController.test.ts
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-517

#529 CUIRA-294 allowed s2s validation
  charts/cui-ra/Chart.yaml
  charts/cui-ra/values.yaml
  config/custom-environment-variables.json
  config/default.json
  config/test.json
  src/main/middlewares/serviceAuthentication.ts
  src/test/unit/tests/middlewares/serviceAuthentication.test.ts
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-529

#536 Fix zaproxy reported issues
  src/main/app.ts
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-536

#534 Linking error to first checkbox
  config/default.json
  src/main/builders/formBuilder.ts
  src/main/processors/formProcessor.ts
  src/main/validators/formValidator.ts
  src/main/views/forms/base.njk
  src/test/unit/data/form-validator-results.json
  src/test/unit/tests/validators/autoCompleteFormValidator.test.ts
  src/test/unit/tests/validators/checkboxOtherFormValidator.test.ts
  src/test/unit/tests/validators/radioOtherFormValidator.test.ts
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-534

#540 CUIRA-327 shutter page link
  src/main/resources/translation/cy/errors/500.json
  src/main/resources/translation/en/errors/500.json
  src/main/views/error/500.njk
Labels: ns:cui, prd:cui, rel:cui-ra-pr-540

#545 CUIRA-177 update contact service info
  src/main/resources/translation/cy/services/ABA5/contact.json
  src/main/resources/translation/cy/services/ABA5/flags.json
  src/main/resources/translation/cy/services/ABA5/footer.json
  src/main/resources/translation/cy/services/ABA5/header.json
  src/main/resources/translation/cy/services/PFL/header.json
  src/main/resources/translation/en/services/ABA5/contact.json
  src/test/functional/features/hello-world.feature
  src/test/functional/features/new-Journey.feature
  src/test/steps/common.ts
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-545
