Repository hmcts/cui-ra, pull requests merged in 2024-06, with the labels that each got.

#595 Suppress ip vulnerability as there is no fix for it yet
  yarn-audit-known-issues
Labels: ns:cui, prd:cui, rel:cui-ra-pr-595

#598 PCQ-1904 cuira fortify scan fix
  src/main/controllers/reviewController.ts
  src/test/unit/tests/controllers/reviewController.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-598

#599 PCQ-1904 test cases added
  src/main/constants/errorMessages.ts
  src/main/controllers/reviewController.ts
  src/test/unit/tests/controllers/reviewController.test.ts
Labels: ns:cui, prd:cui, rel:cui-ra-pr-599
