Repository hmcts/cui-ra, pull requests merged in 2024-05, with the labels that each got.

#576 Address npm audit issues
  .pnp.cjs
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:cui, prd:cui, rel:cui-ra-pr-576

#577 use define version instead of latest
  docker-compose.yml
Labels: ns:cui, prd:cui, rel:cui-ra-pr-577

#575 Update checks.yml
  .github/workflows/checks.yml
Labels: ns:cui, prd:cui, rel:cui-ra-pr-575

#578 Create security.md
  security.md
Labels: ns:cui, prd:cui, rel:cui-ra-pr-578

#579 Add healthcheck to Dockerfile
  Dockerfile
Labels: ns:cui, prd:cui, rel:cui-ra-pr-579

#580 CUIRA-355 address zaproxy issues
  audit.json
  src/main/app.ts
  src/main/modules/helmet/index.ts
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-580

#582 Update audit.json
  audit.json
Labels: ns:cui, prd:cui, rel:cui-ra-pr-582

#583 fixed mock data, added demo and fix validation
  src/main/controllers/demoController.ts
  src/main/controllers/formController.ts
  src/main/demo/data/data-processor-results-welsh.json
  src/main/demo/data/data-processor-results.json
  src/main/demo/data/flags.json
  src/main/processors/formProcessor.ts
  src/main/views/demo.njk
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-583

#585 new demo data
  src/main/controllers/demoController.ts
  src/main/demo/data/data-processor-results-party.json
  src/main/resources/configs/default.json
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-585

#584 added cookie banner and cookie page consent changer
  .pnp.cjs
  package.json
  src/main/assets/js/index.ts
  src/main/modules/helmet/index.ts
  src/main/resources/translation/cy/common.json
  src/main/resources/translation/en/common.json
  src/main/resources/translation/en/static/cookies.json
  src/main/views/cookies-banner.njk
  src/main/views/cookies.njk
  src/main/views/tagmanager/body.njk
  src/main/views/tagmanager/head.njk
  src/main/views/template.njk
  yarn.lock
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-584

#589 redirect back to invoking service if service name pressed
  src/main/views/template.njk
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-589

#587 accessibility wording change and cookie banner welsh translations
  .gitignore
  src/main/resources/translation/cy/common.json
  src/main/resources/translation/cy/static/accessibility.json
  src/main/resources/translation/en/static/accessibility.json
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-587

#588 Cuira 345
  .pnp.cjs
  Jenkinsfile_nightly
  bin/run-crossbrowser-tests.sh
  package.json
  src/test/crossbrowser/SauceLabsReportingHelper.js
  src/test/crossbrowser/saucelabs.conf.js
  src/test/crossbrowser/saucelabs.conf.ts
  src/test/crossbrowser/supportedBrowsers.js
  yarn.lock
Labels: ns:cui, prd:cui, rel:cui-ra-pr-588

#594 dynatrace for prod
  charts/cui-ra/Chart.yaml
  charts/cui-ra/values.aat.template.yaml
  charts/cui-ra/values.preview.template.yaml
  charts/cui-ra/values.yaml
  config/custom-environment-variables.json
  config/default.json
  config/development.json
  config/production.json
  src/main/modules/nunjucks/index.ts
  src/main/views/dynatrace/head.njk
Labels: ns:cui, prd:cui, rel:cui-ra-pr-594
