Repository hmcts/cui-ra, pull requests merged in 2025-05, with the labels that each got.

#701 Remove unnecessary resolution
  .pnp.cjs
  package.json
  yarn.lock
Labels: ns:cui, prd:cui, rel:cui-ra-pr-701

#711 Remove-unnecessray-suppression
  .pnp.cjs
  yarn-audit-known-issues
Labels: ns:cui, prd:cui, rel:cui-ra-pr-711

#710 CUIRA-935 - ‘Add a new support request’ button does not appear
  src/main/views/review.njk
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-710

#716 CUIRA-396 remove extra br element
  src/main/views/overview.njk
  src/main/views/review.njk
Labels: ns:cui, prd:cui, enable_keep_helm, rel:cui-ra-pr-716

#719 CME-535 replace jitpack with azure
  src/test/java/build.gradle
Labels: ns:cui, prd:cui, rel:cui-ra-pr-719
